; Menyembunyikan pesan error dari publik
display_errors = Off
display_startup_errors = Off
log_errors = On
expose_php = Off
session.use_strict_mode = 1

; Menaikkan batas input untuk mencegah peringatan PHP Warning dari pemindai WAS
max_input_vars = 3000