services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: elearning-app
        container_name: elearning_app
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - elearning_network

    nginx:
        image: nginx:stable-alpine
        container_name: elearning_nginx
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - elearning_network
        depends_on:
            - app

    elearning_db:
        image: mysql:8.0
        container_name: elearning_db
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: e-learning
            MYSQL_ROOT_PASSWORD: elearning_secret_2026
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - elearning_network

    phpmyadmin_elearning:
        image: phpmyadmin/phpmyadmin
        container_name: elearning_phpmyadmin
        restart: unless-stopped
        ports:
            - "8082:80"
        environment:
            PMA_HOST: elearning_db
            MYSQL_ROOT_PASSWORD: elearning_secret_2026
        networks:
            - elearning_network
        depends_on:
            - elearning_db

    elearning_redis:
        image: redis:alpine
        container_name: elearning_redis
        restart: unless-stopped
        ports:
            - "6380:6379"
        networks:
            - elearning_network

networks:
    elearning_network:
        driver: bridge

volumes:
    dbdata:
